package ru.tgwatch

import org.junit.Assert.*
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.nio.ByteBuffer
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec

class PortableBackupCodecTest {
    // Generated by the unchanged published-main BackupCodec, in an isolated K2 run.
    private val published = Base64.getDecoder().decode("VEdXQgEJzs6tmn7q7KukUsbpt0VPRQDXl5sQEa8bhYDQIEXR5a1WhT0XbhGeEttHz6/mp+40AiAviIY0TY/X0u7aznAv5dFSi114Mng7RLdR8ANgMMOK3wW0m+Yc05vr2beMIqAV0rfi53w2xzP/wtbPW79Dc5wPOLF3mdDLwvV9gIKQP+xLN/XZGcKDn51dwwme+VHrALDWENEO+NN3XhAgF65b/eFlFwIkw/UKoCGT9axml6HAR0ZLCXO4dzMWhtofLRbNOn1Zg5XCbz0eml/u1yH5I9/2tP0velQxs8c228cpKXQJku8rfAAdEPj7VyPer2Su3mZ1z8wVdRyZnObct3EUXvQCyR7/xuDy")
    private val payload = Base64.getDecoder().decode("VEdEMQAAAYvP5WvoAAAABQALZXZlbnRfc291bmQABHRydWUAD25vdGlmeV9yZWNvdmVyeQAFZmFsc2UADnF1aWV0X2VuZF9ob3VyAAE3ABBxdWlldF9zdGFydF9ob3VyAAIyMgAPdmlicmF0ZV9wYXJ0aWFsAAR0cnVlAAAAAQAAAYvP5WgAAAABi8/lafQAB1BBUlRJQUz//////////wAAAAAAAAACAAAAAQAv0KHQstGP0LfRjCDQstC+0YHRgdGC0LDQvdC+0LLQu9C10L3QsCDtoL3tu7DvuI8=")
    private fun password() = "fixture-pass".toCharArray()
    private fun rejected(block: () -> Unit) { try { block(); fail("Invalid archive accepted") } catch (e: IllegalArgumentException) { assertNull(e.cause) } }
    private fun sample() = BackupSnapshot(123, mapOf("quiet_start_minute" to 1439, "quiet_end_minute" to 1,
        "notify_outage" to false, "notify_partial" to true, "notify_recovery" to false,
        "sound_outage" to true, "sound_partial" to true, "sound_recovery" to false),
        listOf(Observation(0, 1, "OK", Long.MAX_VALUE, Long.MAX_VALUE)), listOf("Копия 🛰️\nжурнал"))

    @Test fun newExportsUseVersionTwoAndRoundTripMinuteAndEventSettings() {
        val snapshot = sample()
        val archive = PortableBackupCodec.encrypt(snapshot, password())
        assertEquals(BackupCodec.encode(snapshot).size + 49, archive.size)
        assertArrayEquals(byteArrayOf(84, 71, 87, 66, 2), archive.copyOfRange(0, 5))
        assertEquals(snapshot, PortableBackupCodec.decrypt(archive, password()))
        assertArrayEquals(password(), password())
        assertEquals(snapshot, BackupCodec.decode(decryptIndependently(archive)))
    }
    @Test fun publishedMainFixtureAndPlaintextJournalMigrateLegacyFallbacks() {
        val imported = PortableBackupCodec.decrypt(published, password())
        assertEquals(1_700_000_001_000, imported.createdAt)
        assertEquals(listOf(Observation(1_700_000_000_000, 1_700_000_000_500, "PARTIAL", -1, 2)), imported.observations)
        assertEquals(listOf("Связь восстановлена 🛰️"), imported.log)
        assertEquals(20, imported.settings.size)
        assertEquals("BALANCED", imported.settings["power_profile"])
        assertEquals(1320, imported.settings["quiet_start_minute"])
        assertEquals(420, imported.settings["quiet_end_minute"])
        assertEquals(true, imported.settings["sound_outage"])
        assertEquals(true, imported.settings["sound_recovery"])
        assertEquals(false, imported.settings["sound_partial"])
        assertEquals(false, imported.settings["notify_recovery"])
        assertEquals(true, imported.settings["notify_outage"])
        assertEquals(false, imported.settings["notify_partial"])
        assertEquals(imported, PortableBackupCodec.decodePublishedPayload(payload))
        assertEquals(imported, PortableBackupCodec.decrypt(PortableBackupCodec.encrypt(imported, password()), password()))
    }
    @Test fun localVersionOneImportsPreserveOptionalKeysAndLegacyEventSound() {
        val snapshot = BackupSnapshot(0, mapOf("event_sound" to true, "quiet_start_minute" to 1379,
            "sound_outage" to false, "notify_recovery" to false), emptyList(), emptyList())
        val imported = PortableBackupCodec.decrypt(BackupCrypto.encrypt(BackupCodec.encode(snapshot), "eightpwd".toCharArray()), "eightpwd".toCharArray())
        assertEquals(snapshot.createdAt, imported.createdAt)
        assertEquals(snapshot.settings + mapOf("notify_outage" to true, "notify_partial" to false,
            "sound_partial" to false, "sound_recovery" to true), imported.settings)
        val empty = PortableBackupCodec.decrypt(BackupCrypto.encrypt(BackupCodec.encode(snapshot.copy(settings = emptyMap())), "eightpwd".toCharArray()), "eightpwd".toCharArray())
        assertEquals(false, empty.settings["sound_recovery"])
        assertFalse(empty.settings.containsKey("quiet_start_minute"))
    }
    @Test fun publishedExplicitEventFlagsOverrideLegacyDefaults() {
        val imported = PortableBackupCodec.decodePublishedPayload(binaryPayload(mapOf("event_sound" to "true",
            "sound_outage" to "false", "sound_recovery" to "false", "sound_partial" to "true",
            "notify_outage" to "false", "notify_partial" to "true")))
        assertEquals(false, imported.settings["sound_outage"])
        assertEquals(false, imported.settings["sound_recovery"])
        assertEquals(true, imported.settings["sound_partial"])
        assertEquals(false, imported.settings["notify_outage"])
        assertEquals(true, imported.settings["notify_partial"])
    }
    @Test fun bothVersionsRejectHeaderCipherTagTamperingWrongPasswordsAndTrailingData() {
        for (archive in listOf(published, PortableBackupCodec.encrypt(sample(), password()))) {
            assertTrue(archive.size > 49)
            rejected { PortableBackupCodec.decrypt(archive, "wrong-secret".toCharArray()) }
            for (offset in listOf(0, 4, 5, 20, 21, 32, 33, archive.lastIndex)) {
                rejected { PortableBackupCodec.decrypt(archive.copyOf().apply { this[offset] = (this[offset].toInt() xor 1).toByte() }, password()) }
            }
            for (size in listOf(0, 4, 32, 48, archive.size - 1)) rejected { PortableBackupCodec.decrypt(archive.copyOf(size), password()) }
            rejected { PortableBackupCodec.decrypt(archive + byteArrayOf(0), password()) }
        }
    }
    @Test fun unsupportedVersionsLimitsAndNewExportPasswordBoundariesRejectBeforeCrypto() {
        for (version in listOf(0, 3, 255)) rejected { PortableBackupCodec.decrypt(ByteArray(49).apply {
            byteArrayOf(84,71,87,66,version.toByte()).copyInto(this) }, password()) }
        for (size in listOf(0, 11, 257)) rejected { PortableBackupCodec.encrypt(sample(), CharArray(size) { 'x' }) }
        for (size in listOf(12, 256)) {
            val pass = CharArray(size) { 'я' }
            assertEquals(sample(), PortableBackupCodec.decrypt(PortableBackupCodec.encrypt(sample(), pass), pass))
        }
        rejected { PortableBackupCodec.decrypt(ByteArray(PortableBackupCodec.MAX_ENVELOPE_BYTES + 1), password()) }
        rejected { PortableBackupCodec.decrypt(ByteArray(4 * 1024 * 1024 + 1).apply { byteArrayOf(84,71,87,66,1).copyInto(this) }, password()) }
        rejected { PortableBackupCodec.decodePublishedPayload(ByteArray(4 * 1024 * 1024 + 1)) }
    }
    @Test fun authenticatedVersionTwoStillRequiresStrictJsonAndVersionOneBinaryRejectsMalformedCounts() {
        rejected { PortableBackupCodec.decrypt(encryptIndependently("{}".toByteArray(), 2), password()) }
        rejected { PortableBackupCodec.decrypt(encryptIndependently(payload, 2), password()) }
        rejected { PortableBackupCodec.decrypt(encryptIndependently(BackupCodec.encode(sample()), 1), password()) }
        rejected { PortableBackupCodec.decodePublishedPayload(payload + byteArrayOf(0)) }
        rejected { PortableBackupCodec.decodePublishedPayload(payload.copyOf(payload.size - 1)) }
        for (count in listOf(-1, 19, Int.MAX_VALUE)) rejected { PortableBackupCodec.decodePublishedPayload(payload.copyOf().apply { ByteBuffer.wrap(this).putInt(12, count) }) }
        for (map in listOf(mapOf("enabled" to "false"), mapOf("interval_sec" to "99999999999999999999"), mapOf("vibrate" to "TRUE"), mapOf("quiet_start_minute" to "1"))) {
            rejected { PortableBackupCodec.decodePublishedPayload(binaryPayload(map)) }
        }
    }
    @Test fun newArchiveSaltAndNonceAreRandomAndLegacyLongPasswordsRemainReadable() {
        val first = PortableBackupCodec.encrypt(sample(), password())
        val second = PortableBackupCodec.encrypt(sample(), password())
        assertEquals(BackupCodec.encode(sample()).size + 49, first.size)
        assertEquals(first.size, second.size)
        assertFalse(first.copyOfRange(5, 21).contentEquals(second.copyOfRange(5, 21)))
        assertFalse(first.copyOfRange(21, 33).contentEquals(second.copyOfRange(21, 33)))
        val pass = CharArray(1024) { 'x' }
        val imported = PortableBackupCodec.decrypt(BackupCrypto.encrypt(BackupCodec.encode(sample()), pass), pass)
        assertEquals(sample().settings, imported.settings)
    }
    @Test fun publishedBinaryRejectsInvalidRecordsDuplicateRowsAndExcessiveJournal() {
        val good = Observation(1, 2, "OK")
        val invalid = listOf(good.copy(at = -1), good.copy(until = 1), good.copy(until = 600_002),
            good.copy(until = 124), good.copy(kind = "OTHER"), good.copy(latencyMs = -2),
            good.copy(latencyMs = 600_001), good.copy(clockEpoch = -1), good.copy(clockEpoch = 1_000_000_001))
        invalid.forEach { rejected { PortableBackupCodec.decodePublishedPayload(binaryPayload(emptyMap(), listOf(it))) } }
        rejected { PortableBackupCodec.decodePublishedPayload(binaryPayload(emptyMap(), listOf(good, good))) }
        for (log in listOf(listOf("x".repeat(513)), listOf("two\nlines"), List(151) { "line" }))
            rejected { PortableBackupCodec.decodePublishedPayload(binaryPayload(emptyMap(), log = log)) }
        for (count in listOf(-1, 65_001, Int.MAX_VALUE)) rejected { PortableBackupCodec.decodePublishedPayload(
            binaryPayload(emptyMap()).apply { ByteBuffer.wrap(this).putInt(16, count) }) }
        rejected { PortableBackupCodec.decodePublishedPayload(binaryPayload(emptyMap()).apply { ByteBuffer.wrap(this).putLong(4, 0) }) }
        rejected { PortableBackupCodec.decrypt(ByteArray(BackupCodec.MAX_PLAINTEXT_BYTES + 50).apply {
            byteArrayOf(84,71,87,66,2).copyInto(this) }, password()) }
    }
    @Test fun genuineLegacyJsonWithNoIndependentFlagsKeepsEventFallbacksAndMinutes() {
        val snapshot = BackupSnapshot(123, mapOf("event_sound" to true, "notify_recovery" to false,
            "quiet_start_minute" to 1379, "quiet_end_minute" to 421), emptyList(), listOf("старый журнал"))
        val pass = "eightpwd".toCharArray()
        val restored = PortableBackupCodec.decrypt(BackupCrypto.encrypt(BackupCodec.encode(snapshot), pass), pass)
        assertEquals(true, restored.settings["sound_outage"])
        assertEquals(true, restored.settings["sound_recovery"])
        assertEquals(false, restored.settings["sound_partial"])
        assertEquals(false, restored.settings["notify_recovery"])
        assertEquals(1379, restored.settings["quiet_start_minute"])
        assertEquals(421, restored.settings["quiet_end_minute"])
        assertEquals(snapshot.log, restored.log)
    }
    private fun binaryPayload(settings: Map<String, String>, rows: List<Observation> = emptyList(), log: List<String> = emptyList()): ByteArray = ByteArrayOutputStream().also { bytes ->
        DataOutputStream(bytes).use { out -> out.writeInt(0x54474431); out.writeLong(123); out.writeInt(settings.size)
            settings.forEach { (key,value) -> out.writeUTF(key); out.writeUTF(value) }; out.writeInt(rows.size)
            rows.forEach { out.writeLong(it.at); out.writeLong(it.until); out.writeUTF(it.kind); out.writeLong(it.latencyMs); out.writeLong(it.clockEpoch) }
            out.writeInt(log.size); log.forEach { out.writeUTF(it) } }
    }.toByteArray()
    private fun decryptIndependently(archive: ByteArray): ByteArray = crypt(archive, true)
    private fun encryptIndependently(plain: ByteArray, version: Int): ByteArray = crypt(byteArrayOf(84,71,87,66,version.toByte()) + ByteArray(28) + plain, false)
    private fun crypt(bytes: ByteArray, decrypt: Boolean): ByteArray {
        val spec = PBEKeySpec(password(), bytes.copyOfRange(5,21), 600_000, 256)
        val key = try { SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).encoded } finally { spec.clearPassword() }
        return try {
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(if (decrypt) Cipher.DECRYPT_MODE else Cipher.ENCRYPT_MODE, SecretKeySpec(key,"AES"), GCMParameterSpec(128,bytes.copyOfRange(21,33)))
            cipher.updateAAD(bytes.copyOfRange(0,33))
            val result = cipher.doFinal(bytes,33,bytes.size-33)
            if (decrypt) result else bytes.copyOfRange(0,33) + result
        } finally { key.fill(0) }
    }
}
